feature:#35-Creation d'une fonction qui trouve le plus petit nombre dans un tableau
Afrogeekacademy/java-algorithms-challenge pull request #44
Opened 2024-04-10 02:20 UTC by Rustyfull

J'ai implemente une petite fonction pour trouver les nombres dans un tableau aussi bine pour les nombres positioves que pour les nombres negatives . Qu'est ce que tu en penses ??

2024-04-10 02:22 UTC, Rustyfull commented
Qu'est ce que vous en pensez de mon implementation

2024-04-10 14:56 UTC, PradermN commented
Super! Que se passe t'il si ta méthode est appelée avec un tableau vide? Tu pourras vérifier voir si cela lève une exception.

2024-04-18 18:28 UTC, carine2107 commented
@Rustyfull, stp pourrais-tu inserer le screenshot de ton resultat dans ton commentaire?

2024-04-21 23:56 UTC, ornellaval commented
Good job.

2024-04-27 08:00 UTC, donchi-donald requested changes

2024-04-27 08:00 UTC, donchi-donald commented on .idea/uiDesigner.xml
je veux juste 2 fichiers en ligne, peux tu stp retirer le file ci?

2024-04-27 13:51 UTC, donchi-donald requested changes

2024-04-27 13:51 UTC, donchi-donald commented on src/main/java/fr/afrogeek/algorithms/KMPMatcher.java
cette classe sert a quoi?

2024-05-14 12:28 UTC, mitchi6 commented
Il serait utile d'ajouter des commentaires internes pour expliquer chaque étape de la fonction, ce qui faciliterait la compréhension pour les autres.

2026-02-10 14:17 UTC, closed without merging