feature/#36-somme-chiffres-dun-nombre
Afrogeekacademy/java-algorithms-challenge pull request #45
Opened 2024-04-11 17:15 UTC by JessyMaurelle

Salut a tous.Jai implemente une methode qui permet de calculer la somme de tous les chiffres d'un nombre.
Jettez  un coup d'oeil si possible.Merci!!

2024-04-11 19:01 UTC, auguste2003 commented
Ton code est trés clair et compréhensif . Il manque juste les commentaires .

2024-04-21 23:50 UTC, ornellaval commented
Hallo jessy,
j ai vu ton code et juste te rappeler de supprimer les autres fichiers en dehors des 2 fichiers sur lequel tu as eu a travailler.
A cela faudrait ajouter les commentaires comme Donald l a mentione pour expliquer ton code. :)
![image](https://github.com/Afrogeekacademy/java-algorithms-challenge/assets/124772767/400f0a90-53ae-4dbc-8968-58d5fe00cf00)

2024-04-27 08:01 UTC, donchi-donald commented
peux tu stp retirer les autres fichiers et juste laisser 2 fichiers?

2024-04-27 08:02 UTC, donchi-donald requested changes

2024-04-27 08:02 UTC, donchi-donald commented on .idea/.gitignore
peux tu stp juste mettre 2 fichiers en ligne?

2024-04-27 10:30 UTC, closed without merging